# File: ats-frontend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ats-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ats-frontend
  template:
    metadata:
      labels:
        app: ats-frontend
    spec:
      containers:
      - name: ats-frontend
        image: your-docker-registry/ats-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi