version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
