trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    echo "Current directory: $(pwd)"
    ls -R
  displayName: 'List directory contents'

- script: |
    cd frontend
    npm ci
    npm run build
    npm test
  displayName: 'Frontend: npm install, build, test'
  workingDirectory: '$(System.DefaultWorkingDirectory)/frontend'

- script: |
    cd backend
    npm ci
    npm run build
    npm test
  displayName: 'Backend: npm install, build, test'
  workingDirectory: '$(System.DefaultWorkingDirectory)/backend'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'