trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure Web App name
  FRONTEND_APP_NAME: 'ats-frontend'  # Replace with your Azure Web App for frontend
  IMAGE_TAG: '$(Build.BuildId)'

steps:
- task: UseNode@1
  inputs:
    version: '14.x'
  displayName: 'Install Node.js 14.x for Frontend'

# Step 1: Build Frontend
- script: |
    cd frontend
    npm ci
    npm run build
  displayName: 'Frontend - Build React Application'

# Step 2: Deploy Frontend
- task: AzureWebApp@1
  inputs:
    appName: $(FRONTEND_APP_NAME)
    package: '$(System.DefaultWorkingDirectory)/frontend/build'
  displayName: 'Deploy Frontend to Azure Web App'
