trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure Web App name
  FRONTEND_APP_NAME: 'ats-frontend'  # Replace with your Azure Web App for frontend
  IMAGE_TAG: '$(Build.BuildId)'

steps:
- task: UseNode@1
  inputs:
    version: '14.x'  # Keep this as it is or consider upgrading to 16.x
  displayName: 'Install Node.js 14.x for Frontend'

# Step 1: Build Frontend
- script: |
    cd frontend
    echo "Cleaning npm cache..."
    npm cache clean --force  # Clean the npm cache for fresh installation
    echo "Running npm install..."
    npm install  # Using npm install instead of npm ci for troubleshooting
    echo "Listing installed packages..."
    ls -al node_modules  # List contents of node_modules for verification
    echo "Running npm run build..."
    npm run build
  displayName: 'Frontend - Build React Application'

# Step 2: Deploy Frontend
- task: AzureWebApp@1
  inputs:
    azureSubscription: '4cd72d6a-f9fa-4350-b5b1-2463b528b598'  # Replace with your Azure subscription name or ID
    appName: $(FRONTEND_APP_NAME)
    package: '$(System.DefaultWorkingDirectory)/frontend/build'
  displayName: 'Deploy Frontend to Azure Web App'
