trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  
- script: |
    npm ci
    npm run build
    npm test
  displayName: 'npm install, build, test'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFileName: $(Build.ArtifactName).zip
    replaceExistingArchive: true

- upload: $(System.ArtifactsPath)\$(Build.BuildId).zip
  artifact: drop

- task: PublishBuildArtifacts@1
  condition: succeeded()
  inputs:
    PathtoPublish: '$(System.ArtifactsPath)\$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
