# File: ats-backend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ats-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ats-backend
  template:
    metadata:
      labels:
        app: ats-backend
    spec:
      containers:
      - name: ats-backend
        image: your-docker-registry/ats-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"