version: '3'
services:
  backend:
    build:
      context: ./  # Adjust if your Dockerfile is located elsewhere
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    # Removed depends_on since the service is external
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHON_SERVICE_URL=https://backend-python-service.onrender.com  # Updated to use the external URL

  python-service:
    build:
      context: ./  # Adjust if your Dockerfile is located elsewhere
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    volumes:
      - .:/app
