name: CI/CD

on:
  push:
    branches: [ main_new ]
  pull_request:
    branches: [ main_new ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Clear NPM Cache
      run: npm cache clean --force
    
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
    
    - name: List Installed Packages
      run: |
        cd frontend
        npm list --depth=0
    
    - name: Build
      run: |
        cd frontend
        npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build
    
    # - name: Show NPM Debug Log on Failure
    #   if: failure()
    #   run: cat /home/runner/.npm/_logs/*.log