name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main_new ]
  pull_request:
    branches: [ main_new ]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    
    environment: AZURE_WEBAPP_PUBLISH_PROFILE  # Specify the environment here

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        cd frontend
        npm install

    - name: Build Frontend
      run: |
        cd frontend
        npm run build

    # Deploy frontend to Azure Web App using Publish Profile
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ats-frontend'  # Replace with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # The secret for the publish profile
        package: ./frontend/build
