name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main_az  # Trigger on specific branch push
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Build the app
        working-directory: frontend
        run: npm run build

      - name: Zip the build output
        run: |
          cd frontend/build
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/release.zip  # Adjust to match exact zip location

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy-frontend

    environment: AZURE_WEBAPP_PUBLISH_PROFILE

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./  # Download to root

      - name: Unzip artifact
        run: unzip frontend/release.zip -d output  # Adjust path if needed

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ats-frontend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./output  # Path to unzipped output folder
